### ISSUE TITLE
Whatsapp share

### ISSUE THREAD

**Issue by 3rsin3rgul** [naturaln0va/VisualActivityViewController#9]
Hello,
Its not sharing image in the whatsapp. How can I handle it?

**Comment by naturaln0va** [comment]
Hello, I'm not sure why there would be an issue with that. In my experience using the system share sheet, which is what this uses, sharing multiple items isn't always supported by various services. Try just sharing the image without any other items. If that doesn't work, there might be an issue with WhatsApp.

**Comment by naturaln0va** [comment]
I just downloaded and tested this out. Using the example project, that has multiple sharing options, I was able to sharing everything to WhatsApp (text, url, image). However when I shared using the last option that shared text, url and image WhatsApp ignored the image and only handled the text and url.

I'm closing this since it's not and issue with the project however feel free to ask any questions on this issue related to this that I might be able to answer.
